#!/usr/bin/env perl
#
# Syntax highlight text using Vim 
# Script based on work by Geoff Richards and Randy Stauner.
# This software is copyright (c) 2026 by Wolfgang Friebel.
#
# License: GPL-2.0-or-later

use warnings;
use strict;
use 5.9.3;
use IO::File;
use File::Copy;
use File::Temp;
use Term::ANSIColor qw(color colorvalid);
use IPC::Open3;
use Getopt::Std;

our ($opt_c, $opt_h, $opt_l, $opt_L);
&getopts('chl:L') || usage();
usage() if $opt_h;

# do a clean up if we get a CTRL-C
our ($tdir,$script_fh, $markup_fh);
$SIG{INT} = sub { if ($tdir) {
	close $script_fh if $script_fh;
	close $markup_fh if $markup_fh;
	unlink $tdir; print "\n"; exit 1 }};

$tdir = $ENV{TMPDIR} || '/tmp';
$tdir = File::Temp->newdir("$tdir/vimcolorXXXX");
my $defaults = set_defaults();
languages(@ARGV) if $opt_L;

my ($file) = shift;
my $filetype = $opt_l;
my $report_colors = $opt_c;

if (! $file or $file eq '-') {
	$file = File::Temp->new(TEMPLATE => 'inputXXXX', DIR => $tdir);
	File::Copy::syscopy(\*STDIN, $file);
}

# get colors from the active color scheme
my $colorfile = File::Temp->new(TEMPLATE => 'colorsXXXX', DIR => $tdir);
system "vim --not-a-term -XZ +hi +q > $colorfile";
open F, $colorfile or die $!;
my ($key, %attrs);
$_=<F>;
while (<F>) {
	next if /^\s*$/;
	next if ! /^\w/;
	s/\e\[\d+C/ /;
	($key, $attrs{$key||'none'}) = ($1, $2) if /^(\w+)\s+([^x]*)xxx/;
}
close F;
my $reset = color('reset');

# allow the environment to overwrite:
if ($ENV{VIMCOLOR_ANSI}) {
	my @ADD = split /\s*[=;]\s*/, $ENV{VIMCOLOR_ANSI};
	if (@ADD % 2) {
		warn "### VIMCOLOR_ANSI has wrong content: $ENV{VIMCOLOR_ANSI}\n";
	} else {
		while (@ADD) {
			my ($k, $v) = splice @ADD, -2;
			$attrs{$k} = $reset;
			warn "### invalid color name '$v' ###\n" if ! colorvalid($v);;
			$attrs{$k} = color($v) if colorvalid($v);
		}
	}
}
# Build a lookup table to determine if a syntax exists.
my $syntax = do_markup($defaults, $file, $filetype);

sub set_defaults {
	my $ex = 'vim';
	$ex = 'nvim' if grep{ -e "$_/nvim" } split /:/, $ENV{PATH};
	my @opts = $ex eq 'vim' ? qw(--not-a-term -XZ) : qw(headless);
	return {
		vim_command => $ex,
		vim_options => [@opts, qw(-R -i NONE -u NONE -N -n), "+set nomodeline"],
		vim_let => {perl_include_pod => 1, 'b:is_bash' => 1},
	};
}

# Actually run Vim and turn the script's output into a datastructure.
sub do_markup {
	my ($defaults, $file, $filetype) = @_;

	(my $filename = $file) =~s/"/\\"/g;

	# Create a temp file to put the output in.
	my $out_file = File::Temp->new(TEMPLATE => 'vimcXXXX', DIR => $tdir);
	# Create a temp file for the 'script', which is given to vim
	# with the -s option.
	my $script_file = File::Temp->new(TEMPLATE => 'scriptXXXX', DIR => $tdir);
	open $script_fh, ">$script_file" or die "$!\n";
	my $markup_file = File::Temp->new(TEMPLATE => 'markupXXXX', DIR => $tdir);
	open $markup_fh, ">$markup_file" or die "$!\n";
	my $filetype_set = defined $filetype ? ":set filetype=$filetype" : '';
	my $vim_let = $defaults->{vim_let};

	my $markscript= <<'EOF';
set report=1000000
if !strlen(&filetype)
	filetype detect
endif
syn on
new
set modifiable
set paste
set isprint+=9
wincmd p
let s:end = line("$")
let s:lnum = 1
while s:lnum <= s:end
	let s:line = getline(s:lnum)
	let s:len = strlen(s:line)
	let s:new = ""
	let s:col = 1
	while s:col <= s:len
		let s:startcol = s:col " The start column for processing text
		let s:id = synID(s:lnum, s:col, 1)
		let s:col = s:col + 1
		while s:col <= s:len && s:id == synID(s:lnum, s:col, 1) | let s:col = s:col + 1 | endwhile
		let s:id = synIDtrans(s:id)
		let s:name = synIDattr(s:id, 'name')
		let s:new = s:new . '>' . s:name . '>' . substitute(substitute(substitute(strpart(s:line, s:startcol - 1, s:col - s:startcol), '&', '\&a', 'g'), '<', '\&l', 'g'), '>', '\&g', 'g') . '<' . s:name . '<'
		if s:col > s:len
			break
		endif
	endwhile
	exe "normal \<C-W>pa" . strtrans(s:new) . "\n\e\<C-W>p"
	let s:lnum = s:lnum + 1
	+
endwhile
wincmd p
normal dd
EOF
	print $markup_fh $markscript;
	close $markup_fh;
	my @script_lines = (
		map { "$_\n" }
			# do :edit before :let or the buffer variables may get reset
			":edit $filename",
			(
				map { ":let $_=$vim_let->{$_}" }
				grep { defined	$vim_let->{$_} }
					keys %$vim_let
			),

			':filetype on',
			$filetype_set,
			":source $markup_file",
			":write! $out_file",
			':qall!',
	);

	print $script_fh @script_lines;
	close $script_fh;

	run(
		$defaults->{vim_command},
		@{$defaults->{vim_options}},
		$filename, ("-s" => "$script_file")
	);
	my $data = do { local $/; <$out_file> };

	# Given an array ref ($syntax), we add a new syntax chunk to it, unescaping
	# the text & making sure that consecutive chunks of the same type are merged.
	my ($syntax, $content, %types);
	$data =~ s/\x0D\x0A?/\n/g;
	$data =~ s/<(.*?)<>\1>//g; # repeating blocks of the same type
	for (keys %attrs) {
		$types{$_} = 1 if $data =~ s/>$_>(.*?)<$_</$attrs{$_}$1$reset/g; #coloring
	}
	# first line without the reset sequence
	$types{$1} = 0 if $data =~ s/^>(.*?)>(.*?)<\1</$2/; #no color
	$types{$1} = 0 while $data =~ s/>(.*?)>(.*?)<\1</$reset$2/; #no color
	# Unescape ampersands and pointies, restore escape
	my %s=(l=>'<',g=>'>',a=>'&');
	$data =~s/&([lga])/$s{$1}/g;
	$data =~ s/\^\[/\e/g;
	$data =~ s/\e\[0m\e\[0m/$reset/g;
	# get start and end of file correct
	$data .= $reset if $data;
	print $data if $data;

	return if ! $report_colors;
	print "$reset\n### Report color settings:\n";
	printf "%-20s %s\n", $_, "($attrs{$_}xxx$reset)" for grep {$_ && $attrs{$_}} sort keys %types;
	printf "%-20s %s\n", $_, "color not set" for grep {$_ && (!$attrs{$_} || !$types{$_})} sort keys %types;
}

# This is a subroutine which runs a program.
# It takes a list of the program name and arguments.
sub run {
	my ($prog, @args) = @_;

	{
		my ($in, $out) = (Symbol::gensym(), Symbol::gensym());
		my $err_fh = Symbol::gensym();

		my $pid = IPC::Open3::open3($in, $out, $err_fh, $prog => @args);

		# close these to avoid any ambiguity that might cause this to block
		# (see also the paragraph about "select" in IPC::Open3)
		close($in);
		close($out);

		# read handle before waitpid to avoid hanging on older systems
		my $errout = do { local $/; <$err_fh> };

		my $gotpid = waitpid($pid, 0);
		die "couldn't run the program '$prog'" if $gotpid == -1;
		my $error = $? >> 8;
		if ($error) {
			$errout =~ s/\n+\z//;
			my $details = $errout eq '' ? '' :
										"\n$prog wrote this error output:\n$errout\n";
			die "$prog returned an error code of '$error'$details";
		}
	}
}

sub languages {
	my ($pat) = @_;
	$pat ||= '';
	my $cmds = File::Temp->new(TEMPLATE => 'cmdsXXXX', DIR => $tdir);
	my $typefile = File::Temp->new(TEMPLATE => 'typesXXXX', DIR => $tdir);
	open F, ">$cmds" or die "$!";
	print F "redir! >$typefile|set columns=10000|echo getcompletion('$pat', 'filetype')|q!";
	close F;
	run($defaults->{vim_command}, "@{$defaults->{vim_options}}", '-S', $cmds, $typefile);
	open F, $typefile or die $!;
	$_ = <F>; $_ = <F>;
	s/[\[\]',]//g;
	print "$_\n";
	close F;
	exit;
}

sub usage {
	print <<EOF;
usage: vimcolor [-c] [-l language] [filename]
usage: vimcolor -h
usage: vimcolor -L [pattern]

This program works by running the Vim text editor and getting it to apply its
syntax highlighting (aka 'font-locking') to an input file, and mark pieces of
text according to whether it thinks they are comments, keywords, strings, etc.
The script then reads back this markup and converts it to text marked with
ANSI escape sequences based on the Vim syntax coloring of the input file.

OPTIONS:
    -c report color settings at the end of the program
    -h print this help and exit
    -l specify the type of file Vim should expect, if not recognized correctly
    -L list supported languages (file types) [that match pattern] and exit

ARGUMENT
    filename  name of the file to colorize. If not given or - then STDIN is used

A color scheme set in vim is respected. You can alter the color scheme using
the VIMCOLOR_ANSI environment variable in the format of "SynGroup=color;"
For example:

    VIMCOLOR_ANSI='Comment=green;Statement = magenta; '

EOF
	exit;
}
